package registry

import (
	"path"

	"github.com/coreos/fleet/job"
)

const (
	statePrefix = "/state/"
)

// Get the current PayloadState of the provided Job's Payload
func (r *Registry) getPayloadState(jobName string) *job.PayloadState {
	key := path.Join(keyPrefix, statePrefix, jobName)
	resp, err := r.etcd.Get(key, false, true)

	// Assume the error was KeyNotFound and return an empty data structure
	if err != nil {
		return nil
	}

	var state job.PayloadState
	//TODO: Handle the error generated by unmarshal
	unmarshal(resp.Node.Value, &state)
	return &state
}

// Persist the changes in a provided Machine's Job
func (r *Registry) SavePayloadState(jobName string, jobState *job.PayloadState) {
	key := path.Join(keyPrefix, statePrefix, jobName)
	//TODO: Handle the error generated by marshal
	json, _ := marshal(jobState)
	r.etcd.Set(key, json, 0)
}

// Delete the state from the Registry for the given Job's Payload
func (r *Registry) RemovePayloadState(jobName string) error {
	key := path.Join(keyPrefix, statePrefix, jobName)
	_, err := r.etcd.Delete(key, false)
	return err
}
