package registry

import (
	"encoding/json"
	"errors"
	"fmt"
	"path"
	"time"

	"github.com/coreos/go-etcd/etcd"

	"github.com/coreos/coreinit/job"
	"github.com/coreos/coreinit/machine"
)

const (
	keyPrefix      = "/coreos.com/coreinit/"
	lockPrefix     = "/locks/"
	machinePrefix  = "/machines/"
	requestPrefix  = "/request/"
	schedulePrefix = "/schedule/"
	jobWatchPrefix = "/watch/"
	statePrefix    = "/state/"
)

type Registry struct {
	etcd *etcd.Client
}

func New(client *etcd.Client) (registry *Registry) {
	return &Registry{client}
}

// Add a new JobWatch to coreinit
func (r *Registry) AddJobWatch(watch *job.JobWatch) {
	key := path.Join(keyPrefix, jobWatchPrefix, watch.Payload.Name, "object")
	//TODO: Handle the error generated by marshal
	json, _ := marshal(watch)
	r.etcd.Set(key, json, 0)
}

// Attempt to lock a JobWatch on behalf of a Machine
func (r *Registry) ClaimJobWatch(watch *job.JobWatch, m *machine.Machine, ttl time.Duration) bool {
	key := path.Join(keyPrefix, jobWatchPrefix, watch.Payload.Name, "lock")
	return r.acquireLock(key, m.BootId, ttl)
}

// Attempt to remove a given JobWatch from coreinit
func (r *Registry) RemoveJobWatch(name string) {
	key := path.Join(keyPrefix, jobWatchPrefix, name, "object")
	r.etcd.Delete(key, true)

	// Attempt to stop any Jobs that may have been created by the given JobWatch
	for _, m := range r.GetActiveMachines() {
		name := fmt.Sprintf("%s.%s", m.BootId, name)
		j, _ := job.NewJob(name, nil, nil)
		r.RemoveMachineJob(j, &m)
	}
}

func (r *Registry) SaveJobWatchState(watch *job.JobWatch, state job.JobWatchState, ttl time.Duration) {
	key := path.Join(keyPrefix, statePrefix, watch.Payload.Name)
	//TODO: Handle the error generated by marshal
	json, _ := marshal(state)
	r.etcd.Set(key, json, uint64(ttl.Seconds()))
}

// Attempt to acquire a lock in etcd on an arbitrary string. Returns true if
// successful, otherwise false.
func (r *Registry) acquireLock(key string, context string, ttl time.Duration) bool {
	resp, err := r.etcd.Get(key, false, true)

	//FIXME: Here lies a race condition!

	if resp != nil {
		if resp.Node.Value == context {
			_, err = r.etcd.Update(key, context, uint64(ttl.Seconds()))
			return err == nil
		}
	}

	_, err = r.etcd.Create(key, context, uint64(ttl.Seconds()))
	return err == nil
}

func marshal(obj interface{}) (string, error) {
	encoded, err := json.Marshal(obj)
	if err == nil {
		return string(encoded), nil
	} else {
		return "", errors.New(fmt.Sprintf("Unable to JSON-serialize object: %s", err))
	}
}

func unmarshal(val string, obj interface{}) error {
	err := json.Unmarshal([]byte(val), &obj)
	if err == nil {
		return nil
	} else {
		return errors.New(fmt.Sprintf("Unable to JSON-deserialize object: %s", err))
	}
}
