#!/bin/bash

GEN_PATH="bin/google-api-go-generator"
if [ ! -f ${GEN_PATH} ]; then
	go build -o ${GEN_PATH} code.google.com/p/google-api-go-client/google-api-go-generator
fi

./bin/google-api-go-generator \
    -googleapi_pkg "code.google.com/p/google-api-go-client/googleapi" \
    -api_json_file "schema/v1-alpha.json" \
    -output "schema/v1-alpha-gen.go"
