#!/bin/bash -e

if [ ! -h src/github.com/coreos/fleet ]; then
	mkdir -p src/github.com/coreos/
	ln -s ../../.. src/github.com/coreos/fleet
fi

export GOBIN=${PWD}/bin
export GOPATH=${PWD}

go install github.com/coreos/fleet
go install github.com/coreos/fleet/fleetctl
