#!/bin/bash -e

if [ ! -h gopath/src/github.com/coreos/fleet ]; then
	mkdir -p gopath/src/github.com/coreos/
	ln -s ../../../.. gopath/src/github.com/coreos/fleet
fi

export GOBIN=${PWD}/bin
export GOPATH=${PWD}/gopath

eval $(go env)

if [ ${GOOS} = "linux" ]; then
	echo "Building fleet"
	go install github.com/coreos/fleet
else
	echo "Skipping fleet build"
fi

echo "Building fleetctl"
go install github.com/coreos/fleet/fleetctl
