#!/usr/bin/env bash

set -e

VER=$1
PROJ="fleet"

if [ -z "$1" ]; then
	echo "Usage: ${0} VERSION" >> /dev/stderr
	exit 255
fi

set -u

function setup_env {
	local proj=${1}
	local ver=${2}

	if [ ! -d ${proj} ]; then
		git clone https://github.com/coreos/${proj}
	fi

	pushd ${proj} >/dev/null
		git checkout master
		git fetch --all
		git reset --hard origin/master
		git checkout $ver
	popd >/dev/null
}


function package {
	local target=${1}
	local srcdir="${2}/bin"

	local ccdir="${srcdir}/${GOOS}_${GOARCH}"
	if [ -d ${ccdir} ]; then
		srcdir=${ccdir}
	fi
	local ext=""
	for bin in fleetd fleetctl; do
		cp ${srcdir}/${bin} ${target}/${bin}${ext}
	done

	cp fleet/README.md ${target}/README.md
}

function main {
	mkdir -p release
	cd release
	setup_env ${PROJ} ${VER}

	for os in darwin linux; do
		export GOOS=${os}
		export GOARCH="amd64"

		pushd fleet >/dev/null
			GO_LDFLAGS="-s" ./build
		popd >/dev/null

		TARGET="fleet-${VER}-${GOOS}-${GOARCH}"
		mkdir -p ${TARGET}
		package ${TARGET} ${PROJ}

		if [ ${GOOS} == "linux" ]; then
			tar cfz ${TARGET}.tar.gz ${TARGET}
			echo "Wrote release/${TARGET}.tar.gz"
		else
			zip -qr ${TARGET}.zip ${TARGET}
			echo "Wrote release/${TARGET}.zip"
		fi
	done
}

main
